version: "3.9"

services:
  streamlit:
    build: ./streamlit
    volumes:
      - ./streamlit/files:/app/files
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - deploy_network

  fastapi:
    build: ./fastapi
    ports:
      - "8080:8080"
    volumes:
      - ./fastapi/files:/app/files
      - ./fastapi/weights:/app/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge
